[tool.pytest.ini_options]
# Adiciona o diretório atual ao caminho de busca
pythonpath = ["."]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]

# poetry run pytest